create table user_account (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password_hash varchar(512) not null,
    role varchar(32) not null
);

create table community_group (
    id bigint generated by default as identity primary key,
    organizer_id bigint not null references user_account(id),
    name varchar(255) not null,
    visibility varchar(32) not null,
    description text,
    logo_url varchar(512),
    website varchar(512),
    location varchar(255),
    contact_email varchar(255),
    contact_phone varchar(255),
    contact_address varchar(255)
);

create table meeting (
    id bigint generated by default as identity primary key,
    group_id bigint not null references community_group(id),
    title varchar(255) not null,
    description text,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone,
    mode varchar(32) not null,
    visibility varchar(32) not null,
    location varchar(255),
    meeting_url varchar(512),
    recurrence_rule varchar(255)
);
